[package]
name = "libpostal-sys"
version = "0.1.1"
authors = ["Evgeny Duzhakov <diaevd@gmail.com>"]
description = "Native bindings to the libpostal library"
edition = "2018"
#links = "postal"

[lib]
name = "libpostal_sys"

[dependencies]
libc = "0.2.50"
